spring:
  application:
    name: blog-web
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
 #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /user/register
      - /user/login
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: blog-web-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
redis:
  database: blog
  key:
    user: 'web:user'
    resourceList: 'web:resourceList'
  expire:
    common: 86400 # 24小时
request:
  id: requestId
aliyun:
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
      accessKeyId:  # 访问身份验证中用到用户标识
      accessKeySecret:  # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
      bucketName: blogs-oss # oss的存储空间
      policy:
        expire: 300 # 签名有效期(S)
        maxSize: 10 # 上传文件大小(M)
        callback: http://10.27.40.221:38238/crop/aliyun/oss/callback # 文件上传成功后的回调地址 好像需要公网地址，本地不太行
      dir:
        prefix: blog/images/ # 上传文件夹路径前缀